export const types = {
    // Sync
    FILL_TASKS:  'FILL_TASKS',
    CREATE_TASK: 'CREATE_TASK',
    REMOVE_TASK: 'REMOVE_TASK',
    STAR_TASK:   'STAR_TASK',
    UNSTAR_TASK: 'UNSTAR_TASK',
    EDIT_TASK:   'EDIT_TASK',

    // Async
    FETCH_TASKS_ASYNC: 'FETCH_TASKS_ASYNC',
    CREATE_TASK_ASYNC: 'CREATE_TASK_ASYNC',
    REMOVE_TASK_ASYNC: 'REMOVE_TASK_ASYNC',
    STAR_TASK_ASYNC:   'STAR_TASK_ASYNC',
    UNSTAR_TASK_ASYNC: 'UNSTAR_TASK_ASYNC',
    EDIT_TASK_ASYNC:   'EDIT_TASK_ASYNC',
};
